# Generated by Django 3.0.4 on 2020-03-30 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='alternatif',
            fields=[
                ('kodealternatif', models.CharField(max_length=3, primary_key=True, serialize=False)),
                ('namaalternatif', models.CharField(max_length=25)),
                ('c1', models.IntegerField()),
                ('c2', models.IntegerField()),
                ('c3', models.IntegerField(choices=[(1, 'KURANG MENDUKUNG'), (2, 'CUKUP MENDUKUNG'), (3, 'SANGAT MENDUKUNG')], default=1, max_length=1)),
                ('c4', models.IntegerField(choices=[(1, 'SANGAT PRIORITAS'), (2, 'PRIORITAS'), (3, 'KURANG PRIORITAS')], default=1, max_length=1)),
                ('c5', models.IntegerField(choices=[(1, 'SULIT DIPEROLEH'), (2, 'SEDIKIT MUDAH DIPEROLEH'), (3, 'SANGAT MUDAH DIPEROLEH')], default=1, max_length=1)),
            ],
        ),
    ]
