# Generated by Django 3.0.4 on 2020-04-01 05:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alternatif', '0002_auto_20200330_2052'),
    ]

    operations = [
        migrations.CreateModel(
            name='normalisasi',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kodealternatif', models.CharField(max_length=3)),
                ('c1norm', models.IntegerField()),
                ('c2norm', models.IntegerField()),
                ('c3norm', models.IntegerField()),
                ('c4norm', models.IntegerField()),
                ('c5norm', models.IntegerField()),
            ],
        ),
        migrations.AlterField(
            model_name='alternatif',
            name='c1',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='alternatif',
            name='c2',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='alternatif',
            name='c3',
            field=models.FloatField(choices=[(1, 'KURANG MENDUKUNG'), (2, 'CUKUP MENDUKUNG'), (3, 'SANGAT MENDUKUNG')], default=1),
        ),
        migrations.AlterField(
            model_name='alternatif',
            name='c4',
            field=models.FloatField(choices=[(1, 'SANGAT PRIORITAS'), (2, 'PRIORITAS'), (3, 'KURANG PRIORITAS')], default=1),
        ),
        migrations.AlterField(
            model_name='alternatif',
            name='c5',
            field=models.FloatField(choices=[(1, 'SULIT DIPEROLEH'), (2, 'SEDIKIT MUDAH DIPEROLEH'), (3, 'SANGAT MUDAH DIPEROLEH')], default=1),
        ),
    ]
